# Generated by Django 5.2 on 2025-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmatodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapywebfarmatodo',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
